### ISSUE TITLE
TODO list in navigator

### ISSUE THREAD

**Issue by jhk0530** [shinykorea/corona-sickbed#18]
![image](https://user-images.githubusercontent.com/6457691/76050801-1637f100-5fac-11ea-80a9-5dbce181af0f.png)

- [x] 전체 선택 / 해제  옵션 추가 

![image](https://user-images.githubusercontent.com/6457691/76050921-70d14d00-5fac-11ea-8fb3-5f593ec5fcc9.png)

- [x] 안 쓰이는 탭들 (`환자별`, `환자유입`, `시뮬레이션`, `About`) 삭제 혹은 수정 

![image](https://user-images.githubusercontent.com/6457691/76050975-a24a1880-5fac-11ea-954e-4769ac594aef.png)

- [x] 데이터 업로드 이후 , `input option` hide 필요

**Comment by jhk0530** [comment]
수정 완료. #20
