### ISSUE TITLE
TODO list in 대시보드 DataTable

### ISSUE THREAD

**Issue by jhk0530** [shinykorea/corona-sickbed#19]
![image](https://user-images.githubusercontent.com/6457691/76051093-066cdc80-5fad-11ea-8ff3-49fda93f5fcf.png)

- [x] `rownames`는 안 보여줘도 괜찮을것 같음. ( `1` , `2` )
- [x] 기본 sorting order는 정해지기 전까진 `여유` 가 높은 순으로 
- [x] 사용률의 경우, 기준을 정해서 ex) 0,25,50,75% 색상을 다르게 하는것도 괜찮아 보임.
- [x] 병원 항목에 연락처나 링크 걸어주는 것도 필요해 보임. 

-->

![image](https://user-images.githubusercontent.com/6457691/76051423-091c0180-5fae-11ea-9496-25541c056135.png)

**Comment by jhk0530** [comment]
Before
---

![image](https://user-images.githubusercontent.com/6457691/76140695-75772d80-60a0-11ea-81f9-2b74fc8e33dd.png)

After
---

![image](https://user-images.githubusercontent.com/6457691/76140702-8758d080-60a0-11ea-8c2f-6c93fcda48af.png)


- `rownames` 삭제
- `사용율` 낮은 기준 (`여유` 높은 기준)으로 정렬 
- 색상 vs 길이 둘 중 하나밖에 적용이 안되서, 더 고민 해봐야 할 듯합니다.
- `datatable` font size 늘림
- 맨 오른쪽 칼럼에 대표 번호 추가

- `leaflet`에서 색상 일치 안되던 것 ( 비사용중일때 녹색이 아니라 회색 ) 수정
- `leaflet` zoomlevel 조정
